declare module 'lucide-react' {
  import { FC, SVGProps } from 'react'
  export interface LucideProps extends SVGProps<SVGSVGElement> {
    size?: number | string
    strokeWidth?: number | string
    absoluteStrokeWidth?: boolean
  }
  export type LucideIcon = FC<LucideProps>
  export const ArrowRight: LucideIcon
  export const Brain: LucideIcon
  export const Zap: LucideIcon
  export const Shield: LucideIcon
  export const BarChart3: LucideIcon
  export const FileSearch: LucideIcon
  export const Quote: LucideIcon
  export const BookOpen: LucideIcon
  export const Users: LucideIcon
  export const Cpu: LucideIcon
  export const LayoutDashboard: LucideIcon
  export const MessageSquare: LucideIcon
  export const Settings: LucideIcon
  export const User: LucideIcon
  export const ChevronLeft: LucideIcon
  export const ChevronRight: LucideIcon
  export const LogOut: LucideIcon
  export const Bell: LucideIcon
  export const Search: LucideIcon
  export const Moon: LucideIcon
  export const Sun: LucideIcon
  export const Send: LucideIcon
  export const Bot: LucideIcon
  export const Plus: LucideIcon
  export const Trash2: LucideIcon
  export const Edit3: LucideIcon
  export const Clock: LucideIcon
  export const Tag: LucideIcon
  export const FileText: LucideIcon
  export const Copy: LucideIcon
  export const Download: LucideIcon
  export const Upload: LucideIcon
  export const Eye: LucideIcon
  export const EyeOff: LucideIcon
  export const Mail: LucideIcon
  export const Lock: LucideIcon
  export const TrendingUp: LucideIcon
  export const Award: LucideIcon
  export const Activity: LucideIcon
  export const AlertCircle: LucideIcon
  export const CheckCircle: LucideIcon
  export const XCircle: LucideIcon
  export const Info: LucideIcon
  export const RefreshCw: LucideIcon
  export const X: LucideIcon
  export const Check: LucideIcon
  export const ChevronDown: LucideIcon
  export const ChevronUp: LucideIcon
  export const Globe: LucideIcon
  export const Link: LucideIcon
  export const ExternalLink: LucideIcon
  export const Save: LucideIcon
  export const FolderOpen: LucideIcon
  export const Folder: LucideIcon
  export const File: LucideIcon
  export const Image: LucideIcon
  export const Camera: LucideIcon
  export const Mic: LucideIcon
  export const Volume2: LucideIcon
  export const Play: LucideIcon
  export const Pause: LucideIcon
  export const Stop: LucideIcon
  export const SkipForward: LucideIcon
  export const SkipBack: LucideIcon
  export const Maximize: LucideIcon
  export const Minimize: LucideIcon
  export const Star: LucideIcon
  export const Heart: LucideIcon
  export const ThumbsUp: LucideIcon
  export const ThumbsDown: LucideIcon
  export const MessageCircle: LucideIcon
  export const Share: LucideIcon
  export const Share2: LucideIcon
  export const Filter: LucideIcon
  export const SortAsc: LucideIcon
  export const SortDesc: LucideIcon
  export const Grid: LucideIcon
  export const List: LucideIcon
  export const Menu: LucideIcon
  export const MoreVertical: LucideIcon
  export const MoreHorizontal: LucideIcon
  export const Loader: LucideIcon
  export const Loader2: LucideIcon
  export const Terminal: LucideIcon
  export const Code: LucideIcon
  export const Code2: LucideIcon
  export const Database: LucideIcon
  export const Server: LucideIcon
  export const Wifi: LucideIcon
  export const WifiOff: LucideIcon
  export const Key: LucideIcon
  export const Unlock: LucideIcon
  export const AlertTriangle: LucideIcon
  export const HelpCircle: LucideIcon
  export const PieChart: LucideIcon
  export const LineChart: LucideIcon
  export const Home: LucideIcon
  export const Map: LucideIcon
  export const MapPin: LucideIcon
  export const Calendar: LucideIcon
  export const Clock3: LucideIcon
  export const Timer: LucideIcon
  export const Bookmark: LucideIcon
  export const Paperclip: LucideIcon
  export const Scissors: LucideIcon
  export const Pen: LucideIcon
  export const PenLine: LucideIcon
  export const Pencil: LucideIcon
  export const Eraser: LucideIcon
  export const Type: LucideIcon
  export const Bold: LucideIcon
  export const Italic: LucideIcon
  export const Underline: LucideIcon
  export const AlignLeft: LucideIcon
  export const AlignCenter: LucideIcon
  export const AlignRight: LucideIcon
  export const Indent: LucideIcon
  export const Outdent: LucideIcon
  export const Table: LucideIcon
  export const Columns: LucideIcon
  export const Rows: LucideIcon
  export const Layout: LucideIcon
  export const Layers: LucideIcon
  export const Box: LucideIcon
  export const Package: LucideIcon
  export const Truck: LucideIcon
  export const ShoppingCart: LucideIcon
  export const CreditCard: LucideIcon
  export const DollarSign: LucideIcon
  export const Percent: LucideIcon
  export const Hash: LucideIcon
  export const AtSign: LucideIcon
  export const Building: LucideIcon
  export const Building2: LucideIcon
  export const Linkedin: LucideIcon
  export const Palette: LucideIcon
  export const GraduationCap: LucideIcon
  export const FlaskConical: LucideIcon
  export const Microscope: LucideIcon
  export const Beaker: LucideIcon
  export const TestTube: LucideIcon
  export const Atom: LucideIcon
  export const Dna: LucideIcon
  export const Network: LucideIcon
  export const TreePine: LucideIcon
  export const Target: LucideIcon
  export const Trophy: LucideIcon
  export const Medal: LucideIcon
  export const Ribbon: LucideIcon
  export const Sparkles: LucideIcon
  export const Wand2: LucideIcon
  export const Magic: LucideIcon
  export const Lightbulb: LucideIcon
  export const Binary: LucideIcon
  export const CircuitBoard: LucideIcon
  export const Workflow: LucideIcon
  export const GitBranch: LucideIcon
  export const GitCommit: LucideIcon
  export const GitMerge: LucideIcon
  export const GitPullRequest: LucideIcon
  export const Github: LucideIcon
  export const Twitter: LucideIcon
  export const Youtube: LucideIcon
  export const Instagram: LucideIcon
  export const Facebook: LucideIcon
  export const Slack: LucideIcon
  export const MessageSquareDashed: LucideIcon
  export const Inbox: LucideIcon
  export const Mail2: LucideIcon
  export const MailOpen: LucideIcon
  export const Newspaper: LucideIcon
  export const Radio: LucideIcon
  export const Tv: LucideIcon
  export const Monitor: LucideIcon
  export const Laptop: LucideIcon
  export const Smartphone: LucideIcon
  export const Tablet: LucideIcon
  export const Watch: LucideIcon
  export const Headphones: LucideIcon
  export const Speaker: LucideIcon
  export const Printer: LucideIcon
  export const Keyboard: LucideIcon
  export const Mouse: LucideIcon
  export const HardDrive: LucideIcon
  export const MemoryStick: LucideIcon
  export const Battery: LucideIcon
  export const Power: LucideIcon
  export const PowerOff: LucideIcon
  export const RotateCcw: LucideIcon
  export const RotateCw: LucideIcon
  export const ZoomIn: LucideIcon
  export const ZoomOut: LucideIcon
  export const Crop: LucideIcon
  export const Sliders: LucideIcon
  export const SlidersHorizontal: LucideIcon
  export const ToggleLeft: LucideIcon
  export const ToggleRight: LucideIcon
  export const Move: LucideIcon
  export const Grab: LucideIcon
  export const Hand: LucideIcon
  export const MousePointer: LucideIcon
  export const MousePointer2: LucideIcon
  export const Pointer: LucideIcon
  export const Crosshair: LucideIcon
  export const Scan: LucideIcon
  export const QrCode: LucideIcon
  export const Barcode: LucideIcon
  export const NfcIcon: LucideIcon
  export const Bluetooth: LucideIcon
  export const BluetoothConnected: LucideIcon
  export const BluetoothOff: LucideIcon
  export const Cast: LucideIcon
  export const Airplay: LucideIcon
  export const Signal: LucideIcon
  export const SignalHigh: LucideIcon
  export const SignalLow: LucideIcon
  export const SignalMedium: LucideIcon
  export const SignalZero: LucideIcon
  export const Gauge: LucideIcon
  export const Speedometer: LucideIcon
  export const TrendingDown: LucideIcon
  export const AreaChart: LucideIcon
  export const CandlestickChart: LucideIcon
  export const ScatterChart: LucideIcon
  export const RadarIcon: LucideIcon
}
